version: "2"
services:
  iptv:
    image: ditronics/mrstream
    container_name: MrStream
    environment:
      - TZ=Etc/UTC
    volumes:
      - ../opt:/opt
    network_mode: host
    restart: always
